// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZvIyWGU-y7jCkiAAAMkFlDvQcRiqxLr4',
    appId: '1:109721846068:web:a6c011a8723f839a43e561',
    messagingSenderId: '109721846068',
    projectId: 'adminpannel-46e78',
    authDomain: 'adminpannel-46e78.firebaseapp.com',
    databaseURL: 'https://adminpannel-46e78-default-rtdb.firebaseio.com',
    storageBucket: 'adminpannel-46e78.appspot.com',
    measurementId: 'G-JK361W1LML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiGa79im3if3-xdX4WQTKXUubZH9wjyrI',
    appId: '1:109721846068:android:1999c4c371c8a7c043e561',
    messagingSenderId: '109721846068',
    projectId: 'adminpannel-46e78',
    databaseURL: 'https://adminpannel-46e78-default-rtdb.firebaseio.com',
    storageBucket: 'adminpannel-46e78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnCawQGA6IUeO7Jucl1NYC4W0E35NB-Es',
    appId: '1:109721846068:ios:282952eacc19d33843e561',
    messagingSenderId: '109721846068',
    projectId: 'adminpannel-46e78',
    databaseURL: 'https://adminpannel-46e78-default-rtdb.firebaseio.com',
    storageBucket: 'adminpannel-46e78.appspot.com',
    androidClientId: '109721846068-4l0tsq4rif7aqmdk7ijgbqrs6flc11t1.apps.googleusercontent.com',
    iosClientId: '109721846068-ioekf4rvtg2c3q58or4ikt7bu0q99c3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.newtokTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnCawQGA6IUeO7Jucl1NYC4W0E35NB-Es',
    appId: '1:109721846068:ios:282952eacc19d33843e561',
    messagingSenderId: '109721846068',
    projectId: 'adminpannel-46e78',
    databaseURL: 'https://adminpannel-46e78-default-rtdb.firebaseio.com',
    storageBucket: 'adminpannel-46e78.appspot.com',
    androidClientId: '109721846068-4l0tsq4rif7aqmdk7ijgbqrs6flc11t1.apps.googleusercontent.com',
    iosClientId: '109721846068-ioekf4rvtg2c3q58or4ikt7bu0q99c3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.newtokTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZvIyWGU-y7jCkiAAAMkFlDvQcRiqxLr4',
    appId: '1:109721846068:web:3bf71f1cfb3c4bd943e561',
    messagingSenderId: '109721846068',
    projectId: 'adminpannel-46e78',
    authDomain: 'adminpannel-46e78.firebaseapp.com',
    databaseURL: 'https://adminpannel-46e78-default-rtdb.firebaseio.com',
    storageBucket: 'adminpannel-46e78.appspot.com',
    measurementId: 'G-PEEZHFGBLJ',
  );
}
